// ! как нормально деструктуризировать при импорте 
// export enum actionConstants {
//    SET_BOOKS = 'SET_BOOKS',
//    GET_NEW_BOOKS = 'GET_NEW_BOOKS',
//    TOGLE_LOADING = 'TOOGLE_LOADING',
//    SET_TOTAL_COUNT = 'SET_TOTAL_COUNT',
// }

const SET_BOOKS = 'SET_BOOKS';
const GET_NEW_BOOKS = 'GET_NEW_BOOKS';
const TOGLE_LOADING = 'TOOGLE_LOADING';
const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
const SEARCH = 'SEARCH'
const CLEAR_SEARCH_VALUE = 'CLEAR_SEARCH_VALUE'
const CLEAR_TOTAL_COUNT = 'CLEAR_TOTAL_COUNT'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const GET_FULL_BOOK_INFO = 'GET_FULL_BOOK_INFO'
const SET_FULL_BOOK_INFO = 'SET_FULL_BOOK_INFO'
const CLEAR_FULL_BOOK_INFO = 'CLEAR_FULL_BOOK_INFO'

export {
   SET_BOOKS,
   GET_NEW_BOOKS,
   TOGLE_LOADING,
   SET_TOTAL_COUNT,
   SEARCH,
   CLEAR_SEARCH_VALUE,
   CLEAR_TOTAL_COUNT,
   SET_CURRENT_PAGE,
   GET_FULL_BOOK_INFO,
   SET_FULL_BOOK_INFO,
   CLEAR_FULL_BOOK_INFO,
};